version: '3'
services:
  golang:
    image: golang:1.22.3-alpine
    ports:
      - 8080:80
    volumes:
      - type: bind
        source: "."
        target: "/src"
    working_dir: "/src"
    tty: true
    restart: always